/**
 * NEXUS AI — ZIP & Asset Exporter Utility
 * Bundles multi-file generated projects into clean .zip packages directly in the browser
 */

window.NexusZipExporter = {
  async exportFilesAsZip(projectName, filesMap) {
    // If JSZip is available via CDN, use it; otherwise fallback to single file download
    if (typeof JSZip !== "undefined") {
      const zip = new JSZip();
      
      // Add README.md automatically
      zip.file("README.md", `# ${projectName}\n\nGenerated autonomously with **Nexus AI** — One AI. Unlimited Creation.\n\n### How to Run\n1. Open \`index.html\` in your favorite web browser or host on Vercel / Netlify / GitHub Pages.\n2. Enjoy your custom responsive web application!`);

      // Add all project files
      for (const [filePath, content] of Object.entries(filesMap)) {
        zip.file(filePath, content);
      }

      const blob = await zip.generateAsync({ type: "blob" });
      this.triggerDownload(blob, `${projectName.toLowerCase().replace(/[^a-z0-9]/g, "-")}.zip`);
      return true;
    } else {
      // Fallback: download primary index.html
      const mainContent = filesMap["index.html"] || Object.values(filesMap)[0] || "";
      const blob = new Blob([mainContent], { type: "text/html" });
      this.triggerDownload(blob, `${projectName.toLowerCase().replace(/[^a-z0-9]/g, "-")}.html`);
      return true;
    }
  },

  triggerDownload(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },

  exportResumeReport(resume) {
    const reportText = `# ATS Analysis Report: ${resume.data.name}
Generated by Nexus AI on ${new Date().toLocaleDateString()}

Overall ATS Score: ${resume.score} / 100

Sub-Scores:
- Keywords Match: ${resume.data.subScores.keywords}%
- Impact & Action Verbs: ${resume.data.subScores.impact}%
- Formatting & Layout: ${resume.data.subScores.formatting}%
- Skill Depth: ${resume.data.subScores.skills}%
- Structural Flow: ${resume.data.subScores.structure}%

Matched Keywords:
${resume.data.matchedKeywords.map(k => `✓ ${k}`).join("\n")}

Missing Keywords to Target:
${resume.data.missingKeywords.map(k => `✗ ${k}`).join("\n")}

Recommended Improvements:
${resume.data.suggestions.map((s, idx) => `${idx + 1}. [${s.section}] ${s.type}\n   Current: ${s.current}\n   Improved: ${s.improved}\n`).join("\n")}
`;

    const blob = new Blob([reportText], { type: "text/markdown" });
    this.triggerDownload(blob, `ATS-Report-${resume.data.role.replace(/[^a-zA-Z0-9]/g, "-")}.md`);
  }
};
